In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("nkwentraders.csv")

In [7]:
df.head()

,TransactionID,Date,Product,Category,Quantity,UnitPrice_FCFA,TotalSale_FCFA,PaymentMethod,SalesRep,CustomerType
0,NKW-0001,2026-02-07,Rice 50kg,Grains,1.0,34928.0,34928.0,Bank Transfer,Divine K.,Walk-in
1,NKW-0002,2026-04-13,Onions 1kg,Produce,12.0,685.0,8220.0,Mobile Money,Florence A.,Wholesale
2,NKW-0003,2026-04-11,Salt 1kg,Groceries,11.0,297.0,3267.0,Orange Money,Beatrice T.,Walk-in
3,NKW-0004,2026-01-01,Bread (loaf),Bakery,13.0,591.0,7683.0,Bank Transfer,Divine K.,Wholesale
4,NKW-0005,2026-02-14,Beans (White),Grain,6.0,915.0,5490.0,Mobile Money,Beatrice T.,Walk-in

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TransactionID   500 non-null    object
 1   Date            500 non-null    object
 2   Product         500 non-null    object
 3   Category        500 non-null    object
 4   Quantity        492 non-null    float64
 5   UnitPrice_FCFA  495 non-null    float64
 6   TotalSale_FCFA  500 non-null    float64
 7   PaymentMethod   490 non-null    object
 8   SalesRep        494 non-null    object
 9   CustomerType    500 non-null    object
dtypes: float64(3), object(7)
memory usage: 39.2+ KB

In [7]:
df.shape

(500, 10)

In [9]:
df.dtypes

TransactionID      object
Date               object
Product            object
Category           object
Quantity          float64
UnitPrice_FCFA    float64
TotalSale_FCFA    float64
PaymentMethod      object
SalesRep           object
CustomerType       object
dtype: object

In [ ]:
df.describe()

         Quantity  UnitPrice_FCFA  TotalSale_FCFA
count  492.000000      495.000000      500.000000
mean    10.991870     4013.123232    40293.494000
std     10.270473     7824.068808    88619.068392
min      1.000000       97.000000      106.000000
25%      5.000000      585.500000     4711.500000
50%     11.000000      905.000000    10920.000000
75%     15.000000     2873.500000    32901.750000
max    200.000000    38216.000000   661143.000000

many columns have missing values.

Quantity: 8 missing

UnitPrice_FCFA: 5 missing

PaymentMethod: 10 missing

SalesRep: 6 missing

but total sale has 500 non null. this means some data in the mentioned columns were not recorded